### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by nahos2585** [danialbehzadi/plugin.video.persianiptv#1]
i'm the original programmer of this addon , please take this down.
سلام ، من برنامه نویس اصلی این برنامه هستم و شما فورکش کردین. لطفا این افزونه رو پاک کنید ...

**Comment by danialbehzadi** [comment]
Hi. Thanks a lot for developing such a nice base. This is a fork of a GPL licensed project and original codes are referenced to the original author, so there's no need for it to be taken down at all.

در ۱۰ فوریهٔ ۲۰۱۷ ۱۶:۲۳:۱۷ (GMT+03:30)، FTABoy <notifications@github.com> نوشت:
>i'm the original programmer of this addon , please take this down.
>سلام ، من برنامه نویس اصلی این برنامه هتسم و شما فورکش کردین. لطفا این
>افزونه رو پاک کنید ...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/danialbehzadi/plugin.video.persianiptv/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hadisaber** [comment]
Salam Danial Jan,
Man barname nevis nistam, serfan jahate konjkavi modati tu file haye barnameye shoma gashti mizadam, akharin activitim ham barmigarde be sale gozshte, dar hale hazer ham hich gune estefadeyi az kari ke shoma kheili vasash zahmat keshidid nemikonam va albate hichvaght nakardam.
behetun tabrik migam, karetun kheili herfeyi hastesh.
Arezooye movafaghiat baraye shoma
Hadi Saber
